### ISSUE TITLE
Crash when generating heatmap

### ISSUE THREAD

**Issue by adryyandc** [NVIDIA/sentiment-discovery#24]
I put the next text in a text file and run:

`python3 generate.py --load_model imdb_clf.pt --gen_length -1 --visualize --text "$(cat review.txt)`

review.txt cointains:

`Unsurprisingly, this motivation dries up as soon as Deadpool goes on his first X-mission (while wearing a hilarious trainee T-shirt, as if he were a red-shirting freshman on a football team). In trying to protect the confused teen mutant Russell (played by Julian Dennison from the brilliant Hunt For The Wilderpeople), Deadpool screws up—and sets into motion events that catch the eye of time-traveling ass-kicker Cable (Josh Brolin).`

While for many paragraphs it works producing nice heat-map, for this text i get the following error:
```
Traceback (most recent call last):
  File "generate.py", line 230, in <module>
    chrs, vals = process_text(args.text, model, input, args.temperature, neuron, mask, args.overwrite, polarity)
  File "generate.py", line 154, in process_text
    ch, val = model_step(model, input, neuron, mask, overwrite, polarity)
  File "generate.py", line 129, in model_step
    out, _ = model(input)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/work/sentiment-discovery/model/model.py", line 36, in forward
    output, hidden = self.rnn(emb, reset_mask=reset_mask)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/lib/python3.6/site-packages/apex-0.1-py3.6.egg/apex/RNN/RNNBackend.py", line 149, in forward
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/lib/python3.6/site-packages/apex-0.1-py3.6.egg/apex/RNN/cells.py", line 37, in forward
  File "/root/anaconda3/lib/python3.6/site-packages/apex-0.1-py3.6.egg/apex/RNN/cells.py", line 62, in mLSTMCell
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 994, in linear
    output = input.matmul(weight.t())
RuntimeError: cublas runtime error : the GPU program failed to execute at /opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCBlas.cu:249
/opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorIndex.cu:306: void indexSelectSmallIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [0,0,0], thread: [32,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
[...]
```

Note i installed PyTorch 0.4.0 with conda.

**Comment by raulpuric** [comment]
That's rather peculiar.

This error looks like it might be generated asynchronously from the device, and my best guess is that it's due to some sort of indexing error in the embedding layer, possibly due to a weird python text encoding error.

Let me try running it myself

**Comment by adryyandc** [comment]
It was reproduced each time. Seems that for certain texts it always crash. Some texts work fine every time.

**Comment by dadelani** [comment]
I tried running
python3 generate.py --load_model model/transformer.pt --gen_length -1
 
but I'm having some apex errors
from ..fp16_utils import Fused_Weight_Norm
ImportError: cannot import name 'Fused_Weight_Norm'

anyone that has successfully run generate.py , can you help
