### ISSUE TITLE
setup.py not finding libaten

### ISSUE THREAD

**Issue by rainjacket** [NVIDIA/sentiment-discovery#28]
```
Cloning into 'sentiment-discovery'...
Traceback (most recent call last):
  File "setup.py", line 71, in <module>
    libaten = find(torch_dir, re.compile("libaten", re.IGNORECASE).search, False)
  File "setup.py", line 31, in find
    return list(set(collection))
TypeError: 'NoneType' object is not iterable
```

I think it might have been a naming change in the newest version of torch. I changed re.compile("libaten", re.IGNORECASE) to re.compile("aten", re.IGNORECASE) and it seems to be working now.

**Comment by raulpuric** [comment]
Yeah this sounds like a bug we just recently had with our other pytorch projects. 
Looking into this now.

**Comment by raulpuric** [comment]
@csarofeen @mcarilli what was the fix the new CTen update.

**Comment by raulpuric** [comment]
https://github.com/NVIDIA/sentiment-discovery/pull/30
Does this work for you?

**Comment by rainjacket** [comment]
Sorry, I haven't been able to verify this because I've just been running models on my own "fixed" version and haven't pulled for the last few weeks.

**Comment by zfallahnejad** [comment]
@raulpuric #30 didn't work for me.

**Comment by dunce1** [comment]
@raulpuric #30  did not work for me either. Getting following error message: Traceback (most recent call last):
  File "setup.py", line 82, in <module>
    assert libaten, "Could not find PyTorch's libATen."
AssertionError: Could not find PyTorch's libATen.
