### ISSUE TITLE
MemoryError - Amazon dataset

### ISSUE THREAD

**Issue by adryyandc** [NVIDIA/sentiment-discovery#31]
Hi,

I get memory error while trying to train on Amazon aggressively deduplicated data. I have 64 GB of memory installed on my system and a 1080ti installed.

I run command inside an LXD container.

```
root@ub-16-sentiment:~/work/sentiment-discovery# python3 main.py --data /home/adrianc/work/Sentiment/dataset/amazon/aggressive_dedup.json --lazy --loose_json --text_key reviewText --label_key overall --num_shards 1002 --optim Adam --split 1000,1,1
configuring data
Traceback (most recent call last):
  File "main.py", line 135, in <module>
    train_data, val_data, test_data = data_config.apply(args)
  File "/root/work/sentiment-discovery/configure_data.py", line 16, in apply
    return make_loaders(opt)
  File "/root/work/sentiment-discovery/configure_data.py", line 63, in make_loaders
    train = data_utils.make_dataset(**data_set_args)
  File "/root/work/sentiment-discovery/data_utils/__init__.py", line 133, in make_dataset
    binarize_sent=binarize_sent, delim=delim, drop_unlabeled=drop_unlabeled, loose=loose)
  File "/root/work/sentiment-discovery/data_utils/__init__.py", line 103, in handle_lazy
    binarize_sent=binarize_sent, delim=delim, drop_unlabeled=drop_unlabeled, ds=data_set)
  File "/root/work/sentiment-discovery/data_utils/__init__.py", line 54, in get_lazy
    make_lazy(processed_path, ds.X, data_type=data_shard)
  File "/root/work/sentiment-discovery/data_utils/lazy_loader.py", line 33, in make_lazy
    f.write(''.join(strs))
MemoryError
```

The problem is memory usage get's beyond 64 GB.

Regards,
Adrian

**Comment by raulpuric** [comment]
Would you mind trying this for the make lazy function?

```
def make_lazy(path, strs, data_type='data'):
    """make lazy version of file"""
    lazypath = get_lazy_path(path)
    if not os.path.exists(lazypath):
        os.makedirs(lazypath)
    datapath = os.path.join(lazypath, data_type)
    lenpath = os.path.join(lazypath, data_type+'.len.pkl')
    if not torch.distributed._initialized or torch.distributed.get_rank() == 0:
        with open(datapath, 'w') as f:
            str_ends = []
            str_cnt = 0
            for s in strs:
                f.write(s)
                str_cnt += len(s)
                str_ends.append(str_cnt)
        pkl.dump(str_ends, open(lenpath, 'wb'))
    else:
        while not os.path.exists(lenpath):
            time.sleep(1)
```

**Comment by adryyandc** [comment]
That function fixed the error, but i get another error:

```
root@ub-16-sentiment:~/work/sentiment-discovery# python3 main.py --data /home/adrianc/work/Sentiment/dataset/amazon/aggressive_dedup.json --lazy --loose_json --text_key reviewText --label_key overall --num_shards 1002 --optim Adam --split 1000,1,1
configuring data
Creating mlstm
* number of parameters: 86294784
Traceback (most recent call last):
  File "main.py", line 303, in <module>
    val_loss = train(total_iters)
  File "main.py", line 233, in train
    for i, batch in enumerate(train_data):
  File "/root/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 451, in __iter__
    return _DataLoaderIter(self)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 239, in __init__
    w.start()
  File "/root/anaconda3/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/root/anaconda3/lib/python3.6/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/root/anaconda3/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/root/anaconda3/lib/python3.6/multiprocessing/popen_fork.py", line 26, in __init__
    self._launch(process_obj)
  File "/root/anaconda3/lib/python3.6/multiprocessing/popen_fork.py", line 73, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
```
Adrian

**Comment by raulpuric** [comment]
Let me find a machine with 64GB to repro. 
What is LXD?

**Comment by adryyandc** [comment]
lxd --version
2.18 
with ubuntu 16.04 and installed tools via conda.

Do you think this is related to GPU memory? I can do some verification!

**Comment by adryyandc** [comment]
Never mind, it got fixed when i installed the latest GPU driver:

`wget https://us.download.nvidia.com/XFree86/Linux-x86_64/390.67/NVIDIA-Linux-x86_64-390.67.run`

**Comment by adryyandc** [comment]
Now i get this error:

```
root@ub-16-sentiment:~/work/sentiment-discovery# python3 main.py --data /home/adrianc/work/Sentiment/dataset/amazon/aggressive_dedup.json --lazy --loose_json --text_key reviewText --label_key overall --num_shards 1002 --optim Adam --split 1000,1,1
configuring data
Creating mlstm
* number of parameters: 86294784
main.py:266: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  cur_loss = total_loss[0] / args.log_interval
| epoch   1 |     0/1180027 batches | lr 5.00E-04 | ms/batch 5.407E+01 |                   loss 5.55E-02 | ppl     1.06 | loss scale     1.00
Traceback (most recent call last):
  File "main.py", line 303, in <module>
    val_loss = train(total_iters)
  File "main.py", line 233, in train
    for i, batch in enumerate(train_data):
  File "/root/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 286, in __next__
    return self._process_next_batch(batch)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 307, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
TypeError: function takes exactly 5 arguments (1 given)

```

**Comment by raulpuric** [comment]
Hmmm. Someone else seems to be getting the same issue with the latest pytorch version. Let me look into this a little bit more.

**Comment by adryyandc** [comment]
Ok.
I installed it with conda to be truth:
root@ub-16-sentiment:~/work/sentiment-discovery# conda list | grep pytorch
cuda90                    1.0                  h6433d27_0    pytorch
pytorch                   0.4.0           py36_cuda9.0.176_cudnn7.1.2_1  [cuda90]  pytorch

**Comment by raulpuric** [comment]
So I am not able to get the same error  while on master in my container.

There's several things to try here:
* can you try running simply `python main.py --lazy` and let me know what you get.
* I will try and use the public pt0.4 container
* can you try installing with `pip` instead of `conda`
* in configure_data.py can you try running with `num_workers: 0` and/or `pin_memory: False` in line 34
```    
data_loader_args = {'num_workers': 1, 'shuffle': opt.shuffle, 'batch_size': batch_size,
            'pin_memory': True, 'transpose': opt.transpose, 'distributed': opt.world_size > 1,
            'rank': opt.rank, 'world_size': opt.world_size, 'drop_last': opt.world_size > 1}```

**Comment by adryyandc** [comment]
I will tomorrow when i get to work.

**Comment by raulpuric** [comment]
Let me also know if this PR works for you.
https://github.com/NVIDIA/sentiment-discovery/pull/32

This works for me on the public pt0.4 container.

**Comment by adryyandc** [comment]
With the lazy patch i get the following error:

```
root@ub-16-sentiment:~/work/sentiment-discovery# python3 main.py --data /home/adrianc/work/Sentiment/dataset/amazon/aggressive_dedup.json --lazy --loose_json --text_key reviewText --label_key overall --num_shards 1002 --optim Adam --split 1000,1,1
configuring data
Traceback (most recent call last):
  File "main.py", line 135, in <module>
    train_data, val_data, test_data = data_config.apply(args)
  File "/root/work/sentiment-discovery/configure_data.py", line 16, in apply
    return make_loaders(opt)
  File "/root/work/sentiment-discovery/configure_data.py", line 63, in make_loaders
    train = data_utils.make_dataset(**data_set_args)
  File "/root/work/sentiment-discovery/data_utils/__init__.py", line 133, in make_dataset
    binarize_sent=binarize_sent, delim=delim, drop_unlabeled=drop_unlabeled, loose=loose)
  File "/root/work/sentiment-discovery/data_utils/__init__.py", line 112, in handle_lazy
    binarize_sent=binarize_sent, delim=delim, drop_unlabeled=drop_unlabeled)
  File "/root/work/sentiment-discovery/data_utils/__init__.py", line 56, in get_lazy
    return lazy_array_loader(processed_path, data_type=data_shard)
  File "/root/work/sentiment-discovery/data_utils/lazy_loader.py", line 68, in __init__
    self.read_lock = Lock()
NameError: name 'Lock' is not defined
```

**Comment by raulpuric** [comment]
My apologies. I just added back the import statement now.

The first command indicates to me that this is specific to the amazon dataset or `--loose_json` flag. Let me re download a a fresh copy of the amazon dataset, and test it myself.

Thanks for your patience.

**Comment by raulpuric** [comment]
try #32 again. Fixed the UnicodeDecodeError I believe.

**Comment by adryyandc** [comment]
Seems working now, at least for a 100 batches.

**Comment by raulpuric** [comment]
Awesome. Going to merge the change in then.
