### ISSUE TITLE
IndexError during training of language model

### ISSUE THREAD

**Issue by stefan-it** [NVIDIA/sentiment-discovery#5]
Hi,

I wanted to train a language model from the Stanford Sentiment Treebank with this command:

```bash
(pyt) stefan@omega:/tmp/stefan_pytorch/sentiment-discovery> python text_reconstruction.py -experiment_dir ./experiments -experiment_name mlstm -model_dir model -cuda \
> -embed_size 64 -rnn_size 4096 -layers 1 -weight_norm -lstm_only -rnn_type mlstm -dropout 0 -persist_state 1 \
> -seq_length 256 -batch_size 32 -lr 0.000125 --optimizer_type=Adam -lr_scheduler LinearLR -epochs 1  \
> -train data/binary_sst/train.csv -valid data/binary_sst/val.csv -test data/binary_sst/test.csv \
> -data_set_type csv -lazy -text_key sentence
```

 But then the following error message appears:

```bash
configuring system
configuring model
64
* number of parameters: 86319360
configuring devices
configuring data
configuring learning
entering training epoch 0
Exiting from training early
Traceback (most recent call last):
  File "text_reconstruction.py", line 238, in <module>
    main()
  File "text_reconstruction.py", line 164, in main
    raise ex
  File "text_reconstruction.py", line 139, in main
    inner_lr=cfg.inner_lr, saver=lambda ext, x: saver('e'+str(e)+ext, x))
  File "text_reconstruction.py", line 45, in run_epoch
    epoch_loop(model, data2use, data_fn, persist=is_training, inner_lr=inner_lr, skip_rule='no')):
  File "/tmp/stefan_pytorch/sentiment-discovery/sentiment_discovery/model/run.py", line 17, in epoch_loop
    for hidden, output in run_model(model, data_iter, data_fn):
  File "/tmp/stefan_pytorch/sentiment-discovery/sentiment_discovery/model/run.py", line 13, in run_model
    yield model(**data_dict)
  File "/tmp/stefan_pytorch/sentiment-discovery/sentiment_discovery/model/model_wrapper.py", line 207, in __call__
    _outputs = self._module(*module_input, **module_args)
  File "/tmp/stefan/anaconda3/envs/pyt/lib/python3.6/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/tmp/stefan_pytorch/sentiment-discovery/sentiment_discovery/model/sequence_model.py", line 200, in forward
    hidden_mask = state_mask[:,t].float().unsqueeze(1)
  File "/tmp/stefan/anaconda3/envs/pyt/lib/python3.6/site-packages/torch/autograd/variable.py", line 78, in __getitem__
    return Index.apply(self, key)
  File "/tmp/stefan/anaconda3/envs/pyt/lib/python3.6/site-packages/torch/autograd/_functions/tensor.py", line 89, in forward
    result = i.index(ctx.index)
IndexError: trying to index 2 dimensions of a 1 dimensional tensor
```

I thought it should also be possible to train a lm model with other (non Amazon) datasets? Thanks :)

**Comment by raulpuric** [comment]
Hi, could you try running this without the lazy flag? We unfortunately did not test the lazy flag on the smaller CSV data sets. We're looking into this, but for the time being please try this and let us know if this works or not. Thanks!

**Comment by raulpuric** [comment]
@stefan-it change the data_set_type flag to unsupervised.

**Comment by stefan-it** [comment]
Using the latest 8adb455411f81ce14332c005e9130bb76898deab

it gives the following error message:

```bash
Traceback (most recent call last):
  File "text_reconstruction.py", line 16, in <module>
    from sentiment_discovery import modules
  File "/tmp/stefan_pytorch/sentiment-discovery/sentiment_discovery/__init__.py", line 2, in <module>
    import sentiment_discovery.data_utils
  File "/tmp/stefan_pytorch/sentiment-discovery/sentiment_discovery/data_utils/__init__.py", line 5, in <module>
    from .preprocess import process_str, tokenize_str_batch, tokenize_text_file
ImportError: cannot import name 'tokenize_text_file'
```

**Comment by stefan-it** [comment]
This function was removed with https://github.com/NVIDIA/sentiment-discovery/commit/806e542043c4aada028236c8928f917f9d855c5c#diff-017a4bfb5881836d218a693254534416

**Comment by stefan-it** [comment]
With this small patch (removing `tokenize_text_file`):

```diff
diff --git a/sentiment_discovery/data_utils/__init__.py b/sentiment_discovery/data_utils/__init__.py
index ae9166a..8076ebf 100755
--- a/sentiment_discovery/data_utils/__init__.py
+++ b/sentiment_discovery/data_utils/__init__.py
@@ -2,7 +2,7 @@ import os
 
 from .samplers import BatchSampler, DistributedBatchSampler, TransposedSampler
 from .loaders import DataLoader
-from .preprocess import process_str, tokenize_str_batch, tokenize_text_file
+from .preprocess import process_str, tokenize_str_batch
 from .datasets import unsupervised_dataset, json_dataset, csv_dataset, split_ds
 from .cache import array_cache
 from .lazy_loader import exists_lazy, make_lazy, lazy_array_loader
```

This error message comes up (using `unsupervised` das ` data_set_type flag`):

```bash
configuring system
configuring model
64
* number of parameters: 86319360
configuring devices
configuring data
making ds
making ds
Traceback (most recent call last):
  File "text_reconstruction.py", line 238, in <module>
    main()
  File "text_reconstruction.py", line 109, in main
    configure_usage('text_reconstruction.py')
  File "/tmp/schweter_pytorch/sentiment-discovery/cfg/__init__.py", line 19, in configure_usage
    cfg.configure()
  File "/tmp/schweter_pytorch/sentiment-discovery/cfg/config.py", line 37, in configure
    self.data_config.apply(self, opt)
  File "/tmp/schweter_pytorch/sentiment-discovery/cfg/configure_data.py", line 12, in apply
    train, valid, test = make_loaders(cfg, opt)
  File "/tmp/schweter_pytorch/sentiment-discovery/cfg/configure_data.py", line 54, in make_loaders
    valid = data_utils.make_dataset(**eval_set_args)
  File "/tmp/schweter_pytorch/sentiment-discovery/sentiment_discovery/data_utils/__init__.py", line 18, in make_dataset
    label_key=label_key, shard_type=dataset)
  File "/tmp/schweter_pytorch/sentiment-discovery/sentiment_discovery/data_utils/datasets.py", line 129, in __init__
    self.save_processed(ds)
  File "/tmp/schweter_pytorch/sentiment-discovery/sentiment_discovery/data_utils/datasets.py", line 172, in save_processed
    ds.write(self.path)
  File "/tmp/schweter_pytorch/sentiment-discovery/sentiment_discovery/data_utils/datasets.py", line 365, in write
    header = tuple(next(writer_gen))
TypeError: 'str' object is not an iterator
```

**Comment by raulpuric** [comment]
Sorry fixed this in #4141bf4 . Needed to properly specify the kwarg for write. 

Our apologies for not testing unsupervised reconstruction with csvs in more depth. 

We're working on this and the rest of our data utils atm. 

Will keep this open for others' benefit until we're fully certain that it's bug-free.

**Comment by raulpuric** [comment]
We have a partial patch out on 709ce00352021b4341e71e16f384eef645718549. 
Use this instead for now:
```python3 text_reconstruction.py -experiment_dir ./deb -experiment_name mlstm -model_dir model -cuda -embed_size 64 -rnn_size 4096 -layers 1 -weight_norm -lstm_only -rnn_type mlstm -dropout 0 -persist_state 1 -seq_length 256 -batch_size 32 -lr 0.000125 --optimizer_type=Adam -lr_scheduler LinearLR -epochs 1 -train data/binary_sst/unsup.csv -valid data/binary_sst/unsup.csv -test data/binary_sst/unsup.csv -data_set_type unsupervised -text_key sentence```

**Comment by stefan-it** [comment]
Thanks for the patch. It was working, but after some steps the following error message appeared:

```bash
python text_reconstruction.py -experiment_dir ./experiments -experiment_name mlstm -model_dir model -cuda -embed_size 64 -rnn_size 4096 -layers 1 -weight_norm -lstm_only -rnn_type mlstm -dropout 0 -persist_state 1 -seq_length 256 -batch_size 32 -lr 0.000125 --optimizer_type=Adam -lr_scheduler LinearLR -epochs 1  -train data/binary_sst/unsup.csv -valid data/binary_sst/unsup.csv -test data/binary_sst/unsup.csv -data_set_type unsupervised -lazy -text_key sentence
configuring system
configuring model
64
* number of parameters: 86319360
configuring devices
configuring data
making ds
making ds
making ds
configuring learning
entering training epoch 0
e0 0 / 111 loss 5.55E+00 loss avg 5.55E-02 time 7.23E+00 time left 8.0E+02 ch/s avg 1.13E+03 grad_norm 9.0E-01 
saving iter 0 of epoch 0
e0 10 / 111 loss 4.41E+00 loss avg 5.33E-01 time 6.98E+00 time left 7.0E+02 ch/s avg 1.17E+03 grad_norm 1.2E+00 
e0 20 / 111 loss 2.70E+00 loss avg 7.83E-01 time 6.97E+00 time left 6.3E+02 ch/s avg 1.17E+03 grad_norm 2.4E+00 
e0 30 / 111 loss 2.37E+00 loss avg 9.46E-01 time 6.98E+00 time left 5.6E+02 ch/s avg 1.17E+03 grad_norm 8.0E-01 
Exiting from training early
Traceback (most recent call last):
  File "text_reconstruction.py", line 238, in <module>
    main()
  File "text_reconstruction.py", line 164, in main
    raise ex
  File "text_reconstruction.py", line 142, in main
    inner_lr=cfg.inner_lr, saver=lambda ext, x: saver('e'+str(e)+ext, x))
  File "text_reconstruction.py", line 48, in run_epoch
    epoch_loop(model, data2use, data_fn, persist=is_training, inner_lr=inner_lr, skip_rule='no')):
  File "/tmp/stefan_pytorch/sentiment-discovery/sentiment_discovery/model/run.py", line 17, in epoch_loop
    for hidden, output in run_model(model, data_iter, data_fn):
  File "/tmp/stefan_pytorch/sentiment-discovery/sentiment_discovery/model/run.py", line 5, in run_model
    for data in data_iter:
  File "/tmp/stefan/anaconda3/envs/pyt/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 210, in __next__
    return self._process_next_batch(batch)
  File "/tmp/stefan/anaconda3/envs/pyt/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 230, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
TypeError: function takes exactly 5 arguments (1 given)
```

**Comment by stefan-it** [comment]
Ok, without the `-lazy` option the training finishes, but there's a bug in the evaluation phase:

```bash
python text_reconstruction.py -experiment_dir ./experiments -experiment_name mlstm -model_dir model -cuda -embed_size 64 -rnn_size 4096 -layers 1 -weight_norm -lstm_only -rnn_type mlstm -dropout 0 -persist_state 1 -seq_length 256 -batch_size 32 -lr 0.000125 --optimizer_type=Adam -lr_scheduler LinearLR -epochs 1  -train data/binary_sst/unsup.csv -valid data/binary_sst/unsup.csv -test data/binary_sst/unsup.csv -data_set_type unsupervised -text_key sentence
configuring system
configuring model
64
* number of parameters: 86319360
configuring devices
configuring data
making ds
making ds
making ds
configuring learning
entering training epoch 0
e0 0 / 115 loss 5.55E+00 loss avg 5.55E-02 time 7.23E+00 time left 8.2E+02 ch/s avg 1.13E+03 grad_norm 9.4E-01 
saving iter 0 of epoch 0
e0 10 / 115 loss 4.42E+00 loss avg 5.34E-01 time 6.96E+00 time left 7.2E+02 ch/s avg 1.18E+03 grad_norm 1.3E+00 
e0 20 / 115 loss 2.68E+00 loss avg 7.84E-01 time 6.96E+00 time left 6.5E+02 ch/s avg 1.18E+03 grad_norm 2.5E+00 
e0 30 / 115 loss 2.31E+00 loss avg 9.43E-01 time 6.97E+00 time left 5.9E+02 ch/s avg 1.18E+03 grad_norm 6.9E-01 
e0 40 / 115 loss 2.20E+00 loss avg 1.07E+00 time 6.97E+00 time left 5.2E+02 ch/s avg 1.18E+03 grad_norm 6.9E-01 
e0 50 / 115 loss 2.12E+00 loss avg 1.17E+00 time 6.97E+00 time left 4.5E+02 ch/s avg 1.18E+03 grad_norm 4.5E-01 
e0 60 / 115 loss 2.04E+00 loss avg 1.26E+00 time 6.97E+00 time left 3.8E+02 ch/s avg 1.18E+03 grad_norm 4.3E-01 
e0 70 / 115 loss 1.98E+00 loss avg 1.33E+00 time 6.97E+00 time left 3.1E+02 ch/s avg 1.18E+03 grad_norm 4.0E-01 
e0 80 / 115 loss 1.96E+00 loss avg 1.39E+00 time 6.97E+00 time left 2.4E+02 ch/s avg 1.18E+03 grad_norm 4.6E-01 
e0 90 / 115 loss 1.92E+00 loss avg 1.44E+00 time 6.97E+00 time left 1.7E+02 ch/s avg 1.18E+03 grad_norm 4.5E-01 
e0 100 / 115 loss 1.86E+00 loss avg 1.48E+00 time 6.97E+00 time left 9.8E+01 ch/s avg 1.18E+03 grad_norm 5.3E-01 
e0 110 / 115 loss 1.86E+00 loss avg 1.52E+00 time 6.97E+00 time left 2.8E+01 ch/s avg 1.18E+03 grad_norm 5.4E-01 
e0 114 / 115 loss 1.85E+00 loss avg 1.53E+00 time 6.97E+00 time left 0.0E+00 ch/s avg 1.18E+03 grad_norm 5.0E-01 
evaluating epoch 0
e*0 0 / 1 loss 1.92E+00 loss avg 1.92E-02 time 7.97E-01 time left 0.0E+00 ch/s avg 1.03E+04
evaluating epoch 0
e*0 0 / 1 loss 1.74E+00 loss avg 1.74E-02 time 7.72E-01 time left 0.0E+00 ch/s avg 1.06E+04
entering training epoch 1
e1 0 / 115 loss 1.83E+00 loss avg 1.83E-02 time 7.01E+00 time left 8.0E+02 ch/s avg 1.17E+03 grad_norm 5.0E-01 
saving iter 0 of epoch 1
e1 10 / 115 loss 1.80E+00 loss avg 1.91E-01 time 6.96E+00 time left 7.2E+02 ch/s avg 1.18E+03 grad_norm 5.5E-01 
e1 20 / 115 loss 1.81E+00 loss avg 3.44E-01 time 6.97E+00 time left 6.5E+02 ch/s avg 1.18E+03 grad_norm 6.8E-01 
e1 30 / 115 loss 1.75E+00 loss avg 4.78E-01 time 6.97E+00 time left 5.9E+02 ch/s avg 1.18E+03 grad_norm 6.7E-01 
e1 40 / 115 loss 1.72E+00 loss avg 5.97E-01 time 6.97E+00 time left 5.2E+02 ch/s avg 1.18E+03 grad_norm 5.3E-01 
e1 50 / 115 loss 1.71E+00 loss avg 7.02E-01 time 6.97E+00 time left 4.5E+02 ch/s avg 1.18E+03 grad_norm 4.7E-01 
e1 60 / 115 loss 1.66E+00 loss avg 7.94E-01 time 6.97E+00 time left 3.8E+02 ch/s avg 1.18E+03 grad_norm 4.9E-01 
e1 70 / 115 loss 1.65E+00 loss avg 8.76E-01 time 6.97E+00 time left 3.1E+02 ch/s avg 1.18E+03 grad_norm 4.4E-01 
e1 80 / 115 loss 1.64E+00 loss avg 9.48E-01 time 6.97E+00 time left 2.4E+02 ch/s avg 1.18E+03 grad_norm 5.4E-01 
e1 90 / 115 loss 1.60E+00 loss avg 1.01E+00 time 6.97E+00 time left 1.7E+02 ch/s avg 1.18E+03 grad_norm 4.2E-01 
e1 100 / 115 loss 1.55E+00 loss avg 1.07E+00 time 6.97E+00 time left 9.8E+01 ch/s avg 1.18E+03 grad_norm 5.0E-01 
e1 110 / 115 loss 1.57E+00 loss avg 1.12E+00 time 6.97E+00 time left 2.8E+01 ch/s avg 1.18E+03 grad_norm 5.3E-01 
e1 114 / 115 loss 1.56E+00 loss avg 1.13E+00 time 6.97E+00 time left 0.0E+00 ch/s avg 1.18E+03 grad_norm 4.5E-01 
evaluating epoch 1
Exiting from training early
Traceback (most recent call last):
  File "text_reconstruction.py", line 238, in <module>
    main()
  File "text_reconstruction.py", line 164, in main
    raise ex
  File "text_reconstruction.py", line 147, in main
    logger.log_pkl(str(np.mean(val_histories)), 'val_history', 'e%s.pkl' % (e,), 'wb')
  File "/tmp/stefan/anaconda3/envs/pyt/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 2909, in mean
    out=out, **kwargs)
  File "/tmp/stefan/anaconda3/envs/pyt/lib/python3.6/site-packages/numpy/core/_methods.py", line 82, in _mean
    ret = ret / rcount
TypeError: unsupported operand type(s) for /: 'list' and 'int'
```

**Comment by raulpuric** [comment]
Hi, I can't seem to reproduce. Its working for us atm, with or without the flag. We had once run into the numpy error you seem to be reporting, but it's curious that it happens for the second epoch not the first. We're looking into it.
```
configuring system
configuring model
64
* number of parameters: 86319360
configuring devices
configuring data
making ds
making ds
making ds
configuring learning
entering training epoch 0
e0 0 / 115 loss 5.55E+00 loss avg 5.55E-02 time 3.20E+00 time left 3.6E+02 ch/s avg 2.56E+03 grad_norm 9.5E-01
saving iter 0 of epoch 0
e0 10 / 115 loss 2.77E+00 loss avg 4.49E-01 time 1.13E+00 time left 1.2E+02 ch/s avg 7.22E+03 grad_norm 2.0E+00
e0 20 / 115 loss 2.26E+00 loss avg 6.41E-01 time 1.13E+00 time left 1.1E+02 ch/s avg 7.20E+03 grad_norm 6.5E-01
e0 30 / 115 loss 2.14E+00 loss avg 7.89E-01 time 1.14E+00 time left 9.6E+01 ch/s avg 7.21E+03 grad_norm 4.5E-01
e0 40 / 115 loss 2.01E+00 loss avg 9.12E-01 time 1.24E+00 time left 8.4E+01 ch/s avg 7.20E+03 grad_norm 3.7E-01
e0 50 / 115 loss 1.92E+00 loss avg 1.01E+00 time 1.10E+00 time left 7.3E+01 ch/s avg 7.18E+03 grad_norm 3.7E-01
e0 60 / 115 loss 1.86E+00 loss avg 1.10E+00 time 1.15E+00 time left 6.2E+01 ch/s avg 7.19E+03 grad_norm 3.9E-01
e0 70 / 115 loss 1.87E+00 loss avg 1.17E+00 time 1.19E+00 time left 5.0E+01 ch/s avg 7.20E+03 grad_norm 4.9E-01
e0 80 / 115 loss 1.83E+00 loss avg 1.24E+00 time 1.12E+00 time left 3.9E+01 ch/s avg 7.22E+03 grad_norm 4.5E-01
e0 90 / 115 loss 1.76E+00 loss avg 1.29E+00 time 1.15E+00 time left 2.7E+01 ch/s avg 7.22E+03 grad_norm 4.6E-01
e0 100 / 115 loss 1.72E+00 loss avg 1.33E+00 time 1.11E+00 time left 1.6E+01 ch/s avg 7.22E+03 grad_norm 4.0E-01
e0 110 / 115 loss 1.70E+00 loss avg 1.37E+00 time 1.17E+00 time left 4.5E+00 ch/s avg 7.22E+03 grad_norm 4.5E-01
e0 114 / 115 loss 1.68E+00 loss avg 1.38E+00 time 1.21E+00 time left 0.0E+00 ch/s avg 7.22E+03 grad_norm 4.1E-01
evaluating epoch 0
e*0 0 / 1 loss 4.57E-01 loss avg 4.57E-03 time 3.06E-01 time left 0.0E+00 ch/s avg 2.67E+04
evaluating epoch 0
e*0 0 / 1 loss 4.35E-01 loss avg 4.35E-03 time 2.66E-01 time left 0.0E+00 ch/s avg 3.08E+04
entering training epoch 1
e1 0 / 115 loss 1.68E+00 loss avg 1.68E-02 time 1.22E+00 time left 1.4E+02 ch/s avg 6.74E+03 grad_norm 4.3E-01
saving iter 0 of epoch 1
e1 10 / 115 loss 1.66E+00 loss avg 1.76E-01 time 1.12E+00 time left 1.2E+02 ch/s avg 7.32E+03 grad_norm 5.3E-01
e1 20 / 115 loss 1.58E+00 loss avg 3.16E-01 time 1.19E+00 time left 1.1E+02 ch/s avg 7.23E+03 grad_norm 5.0E-01
e1 30 / 115 loss 1.62E+00 loss avg 4.41E-01 time 1.20E+00 time left 9.6E+01 ch/s avg 7.15E+03 grad_norm 3.9E-01
e1 40 / 115 loss 1.56E+00 loss avg 5.52E-01 time 1.12E+00 time left 8.4E+01 ch/s avg 7.21E+03 grad_norm 4.5E-01
e1 50 / 115 loss 1.54E+00 loss avg 6.48E-01 time 1.12E+00 time left 7.2E+01 ch/s avg 7.24E+03 grad_norm 4.0E-01
e1 60 / 115 loss 1.52E+00 loss avg 7.33E-01 time 1.15E+00 time left 6.1E+01 ch/s avg 7.23E+03 grad_norm 4.5E-01
e1 70 / 115 loss 1.52E+00 loss avg 8.08E-01 time 1.14E+00 time left 5.0E+01 ch/s avg 7.23E+03 grad_norm 5.2E-01
e1 80 / 115 loss 1.53E+00 loss avg 8.75E-01 time 1.13E+00 time left 3.9E+01 ch/s avg 7.23E+03 grad_norm 4.9E-01
e1 90 / 115 loss 1.47E+00 loss avg 9.34E-01 time 1.13E+00 time left 2.7E+01 ch/s avg 7.23E+03 grad_norm 4.1E-01
e1 100 / 115 loss 1.45E+00 loss avg 9.86E-01 time 1.11E+00 time left 1.6E+01 ch/s avg 7.24E+03 grad_norm 4.4E-01
e1 110 / 115 loss 1.43E+00 loss avg 1.03E+00 time 1.15E+00 time left 4.5E+00 ch/s avg 7.24E+03 grad_norm 4.8E-01
e1 114 / 115 loss 1.41E+00 loss avg 1.05E+00 time 1.22E+00 time left 0.0E+00 ch/s avg 7.23E+03 grad_norm 4.3E-01
evaluating epoch 1
e*1 0 / 1 loss 3.76E-01 loss avg 3.76E-03 time 3.52E-01 time left 0.0E+00 ch/s avg 2.33E+04
evaluating epoch 1
e*1 0 / 1 loss 3.58E-01 loss avg 3.58E-03 time 4.10E-01 time left 0.0E+00 ch/s avg 2.00E+04
```

**Comment by stefan-it** [comment]
I used the latest version f93837756a68e7d38e85cae1a43232c34fd5a5b0 (without `-lazy`) and this time it worked :)

```bash
making ds
making ds
making ds
configuring learning
entering training epoch 0
e0 0 / 115 loss 5.55E+00 loss avg 5.55E-02 time 7.96E+00 time left 9.1E+02 ch/s avg 1.03E+03 grad_norm 9.5E-01
saving iter 0 of epoch 0
e0 10 / 115 loss 4.44E+00 loss avg 5.34E-01 time 6.96E+00 time left 7.2E+02 ch/s avg 1.18E+03 grad_norm 1.3E+00
e0 20 / 115 loss 2.67E+00 loss avg 7.85E-01 time 6.97E+00 time left 6.5E+02 ch/s avg 1.18E+03 grad_norm 2.7E+00
e0 30 / 115 loss 2.32E+00 loss avg 9.43E-01 time 6.97E+00 time left 5.9E+02 ch/s avg 1.18E+03 grad_norm 7.6E-01
e0 40 / 115 loss 2.17E+00 loss avg 1.07E+00 time 6.98E+00 time left 5.2E+02 ch/s avg 1.18E+03 grad_norm 5.8E-01
e0 50 / 115 loss 2.13E+00 loss avg 1.17E+00 time 6.97E+00 time left 4.5E+02 ch/s avg 1.18E+03 grad_norm 4.7E-01
e0 60 / 115 loss 2.06E+00 loss avg 1.26E+00 time 6.97E+00 time left 3.8E+02 ch/s avg 1.18E+03 grad_norm 3.9E-01
e0 70 / 115 loss 2.00E+00 loss avg 1.33E+00 time 6.98E+00 time left 3.1E+02 ch/s avg 1.18E+03 grad_norm 4.5E-01
e0 80 / 115 loss 1.94E+00 loss avg 1.39E+00 time 6.97E+00 time left 2.4E+02 ch/s avg 1.18E+03 grad_norm 4.8E-01
e0 90 / 115 loss 1.91E+00 loss avg 1.44E+00 time 6.97E+00 time left 1.7E+02 ch/s avg 1.18E+03 grad_norm 4.3E-01
e0 100 / 115 loss 1.87E+00 loss avg 1.48E+00 time 6.97E+00 time left 9.8E+01 ch/s avg 1.18E+03 grad_norm 5.8E-01
e0 110 / 115 loss 1.83E+00 loss avg 1.52E+00 time 6.97E+00 time left 2.8E+01 ch/s avg 1.18E+03 grad_norm 4.3E-01
e0 114 / 115 loss 1.83E+00 loss avg 1.53E+00 time 6.97E+00 time left 0.0E+00 ch/s avg 1.18E+03 grad_norm 4.9E-01
evaluating epoch 0
e*0 0 / 1 loss 1.76E+00 loss avg 1.76E-02 time 7.96E-01 time left 0.0E+00 ch/s avg 1.03E+04
evaluating epoch 0
e*0 0 / 1 loss 1.95E+00 loss avg 1.95E-02 time 7.71E-01 time left 0.0E+00 ch/s avg 1.06E+04
entering training epoch 1
e1 0 / 115 loss 1.84E+00 loss avg 1.84E-02 time 7.02E+00 time left 8.0E+02 ch/s avg 1.17E+03 grad_norm 4.8E-01
saving iter 0 of epoch 1
e1 10 / 115 loss 1.82E+00 loss avg 1.91E-01 time 6.97E+00 time left 7.2E+02 ch/s avg 1.18E+03 grad_norm 5.2E-01
e1 20 / 115 loss 1.76E+00 loss avg 3.43E-01 time 6.97E+00 time left 6.6E+02 ch/s avg 1.18E+03 grad_norm 6.1E-01
e1 30 / 115 loss 1.75E+00 loss avg 4.79E-01 time 6.97E+00 time left 5.9E+02 ch/s avg 1.18E+03 grad_norm 5.9E-01
e1 40 / 115 loss 1.68E+00 loss avg 5.97E-01 time 6.97E+00 time left 5.2E+02 ch/s avg 1.18E+03 grad_norm 5.2E-01
e1 50 / 115 loss 1.72E+00 loss avg 7.01E-01 time 6.98E+00 time left 4.5E+02 ch/s avg 1.18E+03 grad_norm 4.7E-01
e1 60 / 115 loss 1.68E+00 loss avg 7.94E-01 time 6.97E+00 time left 3.8E+02 ch/s avg 1.18E+03 grad_norm 4.2E-01
e1 70 / 115 loss 1.63E+00 loss avg 8.76E-01 time 6.97E+00 time left 3.1E+02 ch/s avg 1.18E+03 grad_norm 5.2E-01
e1 80 / 115 loss 1.62E+00 loss avg 9.48E-01 time 6.97E+00 time left 2.4E+02 ch/s avg 1.17E+03 grad_norm 4.5E-01
e1 90 / 115 loss 1.62E+00 loss avg 1.01E+00 time 6.97E+00 time left 1.7E+02 ch/s avg 1.17E+03 grad_norm 5.5E-01
e1 100 / 115 loss 1.57E+00 loss avg 1.07E+00 time 6.97E+00 time left 9.8E+01 ch/s avg 1.17E+03 grad_norm 5.4E-01
e1 110 / 115 loss 1.55E+00 loss avg 1.12E+00 time 6.97E+00 time left 2.8E+01 ch/s avg 1.17E+03 grad_norm 4.6E-01
e1 114 / 115 loss 1.56E+00 loss avg 1.13E+00 time 6.97E+00 time left 0.0E+00 ch/s avg 1.17E+03 grad_norm 5.0E-01
evaluating epoch 1
evaluating epoch 1
```

**Comment by raulpuric** [comment]
fixed in f93837756a68e7d38e85cae1a43232c34fd5a5b0

**Comment by stefan-it** [comment]
With the `lazy` option, training + evaluation suceeded :)
