### ISSUE TITLE
AssertionError in sentiment_transfer

### ISSUE THREAD

**Issue by stefan-it** [NVIDIA/sentiment-discovery#9]
Hi,

I wanted to use the sentiment transfer script + load my pretrained lm model. But this fails:

```bash
python3 sentiment_transfer.py -experiment_dir ./experiments -experiment_name mlstm -model model -cuda -train data/binary_sst/unsup.csv -valid data/binary_sst/unsup.csv -test data/binary_sst/unsup.csv -text_key sentence -label_key label -load_model e1.pt
configuring system
configuring model
64
Traceback (most recent call last):
  File "sentiment_transfer.py", line 119, in <module>
    configure_usage('sentiment_transfer.py')
  File "/tmp/stefan_pytorch/sentiment-discovery/cfg/__init__.py", line 19, in configure_usage
    cfg.configure()
  File "/tmp/stefan_pytorch/sentiment-discovery/cfg/config.py", line 35, in configure
    self.model_config.apply(self, opt)
  File "/tmp/stefan_pytorch/sentiment-discovery/cfg/configure_model.py", line 32, in apply
    lstm_only=lstm_only, saved_path=saved_path)
  File "/tmp/stefan_pytorch/sentiment-discovery/sentiment_discovery/model/__init__.py", line 23, in make_model
    chkpt = restore(model, saved_path)
  File "/tmp/stefan_pytorch/sentiment-discovery/sentiment_discovery/model/serialize.py", line 35, in restore
    assert num_params == len(model.parameters())
AssertionError
```

**Comment by raulpuric** [comment]
If you trained a model with `weight_norm` and `lstm_only` you have to use both those flags when transferring to sentiment analysis.
```
python3 sentiment_transfer.py -experiment_dir ./experiments -experiment_name mlstm -model model -cuda -train data/binary_sst/unsup.csv -valid data/binary_sst/unsup.csv -test data/binary_sst/unsup.csv -text_key sentence -label_key label -load_model e1.pt -weight_norm -lstm_only
```

We're pushing a v0 release in a couple of hours that should fix most of the bugs people have brought to our attention.

Note that you will probably be dissapointed with the results as we were not able to train a model on the SST that transfers reasonably (even to itself). This is most likely due to the limited data of the SST task
